let products = [
    { productId: 'p1',
      productName: 'MINI TEAM WANG LOGO T-SHIRT',
      price: 113.00,
      img: 'img/p1.jpg'},
    { productId: 'p2',
      productName: 'PALM ANGELS X TEAM WANG L/S T-SHIRT',
      price: 460.00,
      img: 'img/p2.jpg'},
    { productId: 'p3',
      productName: 'PALM ANGELS X TEAM WANG NEW NEOPRENE TRACK JACKET',
      price: 960.00,
      img: 'img/p3.jpg'},
    { productId: 'p4',
      productName: 'PALM ANGELS X TEAM WANG NEW NEOPRENE TRACK PANTS',
      price: 845.00,
      img: 'img/p4.jpg'},
    { productId: 'p5',
      productName: 'PALM ANGELS X TEAM WANG S/S T-SHIRT',
      price: 365.00,
      img: 'img/p5.jpg'},
    { productId: 'p6',
      productName: 'TEAM WANG BEANIE',
      price: 65.00,
      img: 'img/p6.jpg'},
    { productId: 'p7',
      productName: 'TEAM WANG DRAWSTRING VELVET STRAIGHT PANT',
      price: 202.00,
      img: 'img/p7.jpg'}
  ];

  export{ products };