let products = [
    { productId: 'p1',
      productName: 'PALM ANGELS X TEAM WANG SOUVENIR JACKETT',
      price: 1410.00,
      img: 'img/p1.jpg'},
    { productId: 'p2',
      productName: 'PALM ANGELS X TEAM WANG L/S T-SHIRT',
      price: 460.00,
      img: 'img/p2.jpg'},
    { productId: 'p3',
      productName: 'PALM ANGELS X TEAM WANG NEW NEOPRENE TRACK JACKET',
      price: 960.00,
      img: 'img/p3.jpg'},
    { productId: 'p4',
      productName: 'PALM ANGELS X TEAM WANG NEW NEOPRENE TRACK PANTS',
      price: 845.00,
      img: 'img/p4.jpg'},
    { productId: 'p5',
      productName: 'PALM ANGELS X TEAM WANG S/S T-SHIRT',
      price: 365.00,
      img: 'img/p5.jpg'},
    { productId: 'p6',
      productName: 'PALM ANGELS X TEAM WANG BOWLING SHIRT',
      price: 765.00,
      img: 'img/p6.jpg'},
    { productId: 'p7',
      productName: 'PALM ANGELS X TEAM WANG CROPPED TEE',
      price: 325.00,
      img: 'img/p7.jpg'}
  ];

  export{ products };